name: Check Linked Issue

on:
  pull_request:
    types: [opened, edited, synchronize, reopened]

jobs:
  check-linked-issue:
    runs-on: ubuntu-latest
    name: Ensure PR has linked issue

    steps:
      - name: Check for linked issue
        uses: actions/github-script@v7
        with:
          script: |
            const { data: pullRequest } = await github.rest.pulls.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.issue.number,
            });

            // Check PR body for issue references
            const prBody = pullRequest.body || '';
            const prTitle = pullRequest.title || '';

            // Common patterns for linking issues
            const issuePatterns = [
              /(?:close[sd]?|fix(?:e[sd])?|resolve[sd]?)\s+#(\d+)/gi,
              /(?:close[sd]?|fix(?:e[sd])?|resolve[sd]?)\s+(?:https?:\/\/github\.com\/[^\/]+\/[^\/]+\/issues\/)(\d+)/gi,
              /#(\d+)/g,
              /(?:issue|issues)\s+#?(\d+)/gi
            ];

            let hasLinkedIssue = false;
            let linkedIssues = [];

            // Check PR body and title for issue references
            const textToCheck = `${prTitle} ${prBody}`;

            for (const pattern of issuePatterns) {
              const matches = textToCheck.matchAll(pattern);
              for (const match of matches) {
                const issueNumber = match[1];
                if (issueNumber) {
                  linkedIssues.push(issueNumber);
                  hasLinkedIssue = true;
                }
              }
            }

            // Also check if PR is linked to issues via GitHub's linking feature
            try {
              const { data: timelineEvents } = await github.rest.issues.listEventsForTimeline({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: context.issue.number,
              });
              
              const connectedEvents = timelineEvents.filter(event => 
                event.event === 'connected' || event.event === 'cross-referenced'
              );
              
              if (connectedEvents.length > 0) {
                hasLinkedIssue = true;
              }
            } catch (error) {
              console.log('Could not fetch timeline events:', error.message);
            }

            if (!hasLinkedIssue) {
              core.setFailed(`❌ This pull request must be linked to an issue.
              
              Please link this PR to an issue by:
              1. Adding "Fixes #<issue-number>" or "Closes #<issue-number>" to the PR description
              2. Using GitHub's UI to link the PR to an existing issue
              3. Referencing the issue number with #<issue-number> in the PR title or description
              
              Example: "Fixes #123" or "Closes #456"`);
            } else {
              console.log(`✅ PR is linked to issue(s): ${linkedIssues.join(', ')}`);
              core.notice(`✅ Pull request is properly linked to issue(s): ${linkedIssues.join(', ')}`);
            }

      - name: Add comment if no linked issue
        if: failure()
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `## ❌ Missing Linked Issue
              
              This pull request needs to be linked to an issue before it can be merged.
              
              ### How to link an issue:
              
              1. **Add keywords to PR description:**
                 - \`Fixes #123\`
                 - \`Closes #456\`
                 - \`Resolves #789\`
              
              2. **Reference issue in PR title or description:**
                 - \`#123\`
                 - \`Issue #456\`
              
              3. **Use GitHub's UI:**
                 - Go to the "Development" section in the right sidebar
                 - Click "Link an issue"
                 - Select the relevant issue
              
              Once you've linked an issue, this check will automatically pass! 🚀`
            })
